// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestOpinionPoll.Models;

public partial class Question
{
    public int QuestionId { get; set; }

    public string QuestionText { get; set; }

    public string Category { get; set; }

    public string Option1 { get; set; }

    public string Option2 { get; set; }

    public string Option3 { get; set; }

    public int Option1Count { get; set; }

    public int Option2Count { get; set; }

    public int Option3Count { get; set; }
}